gotest:
  image: golang:1.13
  before_script:
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
  script:
    - go test ./...
    - golangci-lint run

npmtest:
  image: node:8.16
  before_script:
    - cd ui/static
    - npm install
  script:
    - npm test
    - npx eslint .
